name: Python unittests

on: [push]

env:
  AIRFLOW__CORE__LOAD_EXAMPLES: False

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt  --constraint constraints-3.9.txt; fi
          airflow db init
      - name: Verify airflow
        run: |
          airflow dags list
          airflow connections list
      - name: Unittests
        run: python -m unittest discover tests
      - name: Coverage
        run: |
          python -m pip install coverage
          coverage run -m unittest discover
          coverage report -m --omit=test_tags_delete_or_archive_later/*,tests/*,integration/* --fail-under=50
